project:
  type: book
  output-dir: _site

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
    # number-sections: false

metadata-files:
  - "pages/_chapters.yml"

metadata:
  show-setup: false

book:
  title: "BMS1066/BMS1067 R workshops"
  page-navigation: true
  navbar:
    pinned: true
    logo: images/LLS_SUBBRAND_LOGOS_PNG_Maths_Left_White@600x.png
    title: "R & RStudio"
    right:
      - text: "![](images/stag_logo.png){fig-alt='University of Surrey logo'}"
  page-footer:
    center: |
      Licensed [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)
      ![](https://creativecommons.org/images/deed/cc_icon_black_x2.png){width=25px}
      University of Surrey - Maths and Statistics Advice
  search:
    location: sidebar
  chapters:
    - part: "Welcome"
      chapters:
        - index.qmd
